flake.lock, flake.nix, kiosk-boot.nix
Create an ISO image for running on a kiosk.
=> add kiosk-boot definition

src/index.html, src/styles.css
=> fix: update dialog copies

src/index.html, src/styles.css
=> fix: logos overlapping with stats table

src/game.ts, src/index.html, src/index.ts, src/styles.css
=> feat: select continent dialog

src/index.html, src/index.ts, src/styles.css
=> fix: re-arrange logos

src/game.ts
This is using fixed cost models and maximum execution units, but constructs our transaction using the game redeemer and datum directly in the transaction's cbor format.
This brings down execution of `hydraSend` from 30ms+ to 1-3ms!
Idea and implementation credit goes to @Quantumplation
I just added the script hash and a few bytes.
=> Construct transactions directly on wire format

src/index.html, src/index.ts, src/stats.ts, src/styles.css, src/types.ts
=> feat: leaderboard tables

src/stats.ts
=> feat: display ADA handle on leaderboard is available

src/index.html, src/index.ts, src/stats.ts, src/styles.css
=> feat: highlight user row on leaderboard

src/index.html, src/index.ts, src/speedometer.ts, src/stats.ts, src/styles.css
=> feat: display leaderboard and stats on landing page

.github/workflows/pages.yaml
Once merged, the github action will be triggered on `main` branch. This will build & deploy the main application to `doom.hydra.family`.
=> Deploy doom.hydra.family

src/index.html
=> chore: update html

src/components/DoomCanvas/DoomCanvas.tsx
This pull request includes updates to the `DoomCanvas` component in `src/components/DoomCanvas/DoomCanvas.tsx` to improve the way game data is fetched and handled. The changes involve replacing the `useQuery` hook with the `useMutation` hook from `@tanstack/react-query` and updating the component logic accordingly.
Key changes include:
* Replaced `useQuery` with `useMutation` for fetching game data, including the necessary adjustments to the hook's configuration and usage. [[1]](diffhunk://#diff-684f7a4dc55d5f4b2f1ebd8e90ea6a242b632a130fba45360cbdf3afd851c384L7-R7) [[2]](diffhunk://#diff-684f7a4dc55d5f4b2f1ebd8e90ea6a242b632a130fba45360cbdf3afd851c384R17-R37)
* Updated the `useEffect` dependencies to reflect the changes in data fetching and ensure the effects run correctly based on the …
=> fix: DoomCanvas component is invoking new_game multiple times

src/components/SetNameModal/SetNameModal.tsx, src/constants.ts, src/context/AppContextProvider.tsx, src/context/useAppContext.ts, src/index.css
Reverts cardano-scaling/hydra-doom#67
reverting, something is broken
=> Revert "feat: create slider to select number of player and bots"

public/default.cfg
Turns off moving back and forth with the mouse
=> Set novert to 1

src/components/RegionSelector/RegionSelector.tsx, src/components/RegionSelector/index.ts, src/components/SetNameModal/SetNameModal.tsx, src/constants.ts, src/context/AppContextProvider.tsx, src/context/useAppContext.ts, src/hooks/useBestRegion.ts, src/hooks/useUrls.ts, src/types.ts
This pull request introduces a new `RegionSelector` component and integrates it into the `SetNameModal` component. It also updates the region handling in the application context and related files. The most important changes include the creation of the `RegionSelector` component, modifications to the `SetNameModal` component, updates to the `AppContextProvider`, and changes to the region-related constants and types.
* [`src/components/RegionSelector/RegionSelector.tsx`](diffhunk://#diff-6e2bef1b552ad1ae795d766cbf1f9cb999f96856e862b54b600d28a70cd3014cR1-R44): Created a new `RegionSelector` component that allows users to select a region.
* [`src/components/RegionSelector/index.ts`](diffhunk://#diff-b7fcb01587dc7aef8618e3ae5c6aeb967dc0e560b39ce2c197bd0a3fd1ffdf66R1): Exported the …
=> feat: add region selector

src/components/DoomCanvas/DoomCanvas.tsx
This pull request includes several updates to the `DoomCanvas` component in `src/components/DoomCanvas/DoomCanvas.tsx` to improve the user experience by adding loading states and error handling. The most important changes include adding a loading state, using the `classnames` library for conditional class names, and updating the UI to show loading and error messages.
Enhancements to user experience:
* Added `useState` to manage the loading state and updated the `fetchGameData` mutation to handle errors. [[1]](diffhunk://#diff-684f7a4dc55d5f4b2f1ebd8e90ea6a242b632a130fba45360cbdf3afd851c384L1-R1) [[2]](diffhunk://#diff-684f7a4dc55d5f4b2f1ebd8e90ea6a242b632a130fba45360cbdf3afd851c384R26-R32)
* Imported the `classnames` library to conditionally apply CSS classes based on the loading and …
=> feat: display loading and error messages

src/components/GlobalTPS/GlobalTPS.tsx, src/components/GlobalTotals/GlobalTotals.tsx, src/components/GlobalTotals/index.ts, src/components/InitialView/InitialView.tsx, src/components/Layout/Layout.tsx, src/context/AppContextProvider.tsx, src/context/useAppContext.ts, src/types.ts, src/utils/numbers.ts, src/utils/requests.ts
This pull request introduces new components and refactors existing code to integrate global statistics into the application. The most important changes include adding the `GlobalTotals` component, updating the `AppContext` to fetch and provide global statistics, and modifying the `InitialView` component to display these statistics.
* [`src/components/GlobalTotals/GlobalTotals.tsx`](diffhunk://#diff-e07b3f6d8649115ff0a7406735118bcaa83b3f3642d971431d5009f103071096R1-R41): Added the `GlobalTotals` component to display various global statistics.
* [`src/components/GlobalTotals/index.ts`](diffhunk://#diff-b41f39a6de713fde86ef9b540ec92d69134a54255cd033f95fc9890badcc9433R1): Exported the `GlobalTotals` component.
* [`src/context/AppContextProvider.tsx`](diffhunk://#diff-e49e9ee75a1f24a197cabb5cc3 …
=> feat: display global stats

src/components/SetNameModal/SetNameModal.tsx, src/context/AppContextProvider.tsx, src/context/useAppContext.ts, src/hooks/useUrls.ts
This pull request includes several changes to the `SetNameModal` component and the `AppContextProvider` to enhance functionality and improve code structure. The most important changes involve adding support for selecting the number of bots, updating the context to manage bots, and modifying the URL generation to include player and bot counts.
* Added support for selecting the number of bots and players using radio buttons instead of a range slider. (`src/components/SetNameModal/SetNameModal.tsx`) [[1]](diffhunk://#diff-7d536fb966f6004b2cf8fa54b9600ffc5b40ea175ac57f2ad5046c19c4910c2aL22-R30) [[2]](diffhunk://#diff-7d536fb966f6004b2cf8fa54b9600ffc5b40ea175ac57f2ad5046c19c4910c2aL42-R56) [[3]](diffhunk://#diff-7d536fb966f6004b2cf8fa54b9600ffc5b40ea175ac57f2ad5046c19c4910c2aL105-L130)
* …
=> feat: refactor players and bots selector

src/components/InitialView/InitialView.tsx, src/components/LoginModal/LoginModal.tsx, src/constants.ts, src/context/AppContextProvider.tsx, src/types.ts, src/utils/localStorage.ts, src/utils/requests.ts
This pull request includes a series of changes to replace the use of `session-reference` with `session-id` across multiple files in the codebase. The changes involve updating variable names, function calls, and constants to reflect this new terminology. Additionally, a new authentication refresh function has been introduced.
Key changes include:
* [`src/components/InitialView/InitialView.tsx`](diffhunk://#diff-12b261bd305feca8aaa43403e3335c013ba7326b4645de5967a9d5d37da06d8dL10-R10): Replaced `useSessionReferenceKeyCache` with `useSessionIdKeyCache` and updated related variable names. [[1]](diffhunk://#diff-12b261bd305feca8aaa43403e3335c013ba7326b4645de5967a9d5d37da06d8dL10-R10) [[2]](diffhunk://#diff-12b261bd305feca8aaa43403e3335c013ba7326b4645de5967a9d5d37da06d8dL21-R21) …
=> feat: implement auth refresh

src/components/GameView/GameView.tsx, src/components/SessionStats/SessionStats.tsx, src/components/SessionStats/index.ts, src/components/StatsCard/StatsCard.tsx, src/types.ts, src/utils/requests.ts
This pull request introduces the `SessionStats` component to the `GameView` page, enhancing the display of session statistics. The key changes include the addition of the `SessionStats` component, modifications to the `StatsCard` component to support the new statistics, and updates to the data fetching utilities.
* [`src/components/GameView/GameView.tsx`](diffhunk://#diff-41ded2d05b189214130098a13adda4d0fefd1918047aea5b971478e782d11c05R7): Imported and integrated the `SessionStats` component into the `GameView` layout. [[1]](diffhunk://#diff-41ded2d05b189214130098a13adda4d0fefd1918047aea5b971478e782d11c05R7) [[2]](diffhunk://#diff-41ded2d05b189214130098a13adda4d0fefd1918047aea5b971478e782d11c05R17-R20)
* [`src/components/SessionStats/SessionStats.tsx`](diffhunk://#diff-dd6735cfc5f700659913 …
=> feat: session stats

src/components/MusicPlayer/MusicPlayer.tsx
just needed `currentIndex` to change so it retriggered the react event
=> Make music loop again
